services:
  eda_gateway:
    build:
      context: ./
      dockerfile: ./EDA.Gateway/Dockerfile
    ports:
      - "80:8080"
      - "81:8081"
  eda_client:
    build:
      dockerfile: ./eda.client/Dockerfile
    ports:
      - "83:80"