services:
  eda_gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./EDA.Gateway/Dockerfile
    ports:
      - "80:8080"
      - "81:8081"
  eda_client:
    container_name: client
    build:
      dockerfile: ./eda.client/Dockerfile
    ports:
      - "82:80"
  eda_pictures:
    container_name: pictures
    build:
      dockerfile: ./EDA.Pictures/Dockerfile
    ports:
      - "83:80"
# Kafka
  eda_zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:  
      - zookeeper-data:/data 
      - zookeeper-log:/datalog
  eda_kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - eda_zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    volumes: 
      - kafka-data:/kafka
  eda_kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8084:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
# DB
  eda_postgres_user:
      container_name: postgresql-user
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: p@ssw0rd
        POSTGRES_DB: eda_user
      volumes: 
          - postgres-user-data-db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: always
  eda_postgres_order:
      container_name: postgresql-order
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: p@ssw0rd
        POSTGRES_DB: eda_order
      volumes: 
          - postgres-order-data-db:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      restart: always
  eda_mongo: 
    image: mongo:latest 
    container_name: mongo-catalog
    restart: always 
    environment: 
        MONGO_INITDB_ROOT_USERNAME: mongouser 
        MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd 
    volumes: 
        - mongo-data:/data/db 
    ports: 
        - "27017:27017"
volumes: 
  zookeeper-data: 
  zookeeper-log: 
  kafka-data:
  postgres-user-data-db:
  postgres-order-data-db:
  mongo-data: